-- =========================================
-- ECOREWARDS - BANCO COMPLETO
-- Este script cria a estrutura principal do banco de dados
-- da plataforma EcoRewards.
-- =========================================

-- ========================
-- TABELA: ENDERECO
-- Armazena os endereços utilizados no sistema.
-- No modelo atual, está vinculada ao ponto de coleta.
-- ========================
CREATE TABLE ENDERECO (
    -- Chave primária da tabela ENDERECO
    id_endereco NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome da rua/avenida
    logradouro VARCHAR2(150) NOT NULL,

    -- Número do endereço
    numero VARCHAR2(20) NOT NULL,

    -- Complemento opcional, como bloco/apartamento
    complemento VARCHAR2(100),

    -- Bairro do endereço
    bairro VARCHAR2(100) NOT NULL,

    -- Cidade do endereço
    cidade VARCHAR2(100) NOT NULL,

    -- Estado com sigla de 2 caracteres
    estado VARCHAR2(2) NOT NULL,

    -- CEP do endereço
    cep VARCHAR2(9) NOT NULL
);

-- ========================
-- TABELA: USUARIO
-- Armazena os dados dos usuários da plataforma.
-- ========================
CREATE TABLE USUARIO (
    -- Chave primária da tabela USUARIO
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome completo do usuário
    nome VARCHAR2(120) NOT NULL,

    -- Email único do usuário
    email VARCHAR2(150) NOT NULL UNIQUE,

    -- Senha do usuário
    senha VARCHAR2(255) NOT NULL,

    -- CPF único do usuário
    cpf VARCHAR2(14) NOT NULL UNIQUE,

    -- Telefone de contato
    telefone VARCHAR2(20),

    -- Data de cadastro com valor padrão da data atual
    data_cadastro DATE DEFAULT SYSDATE NOT NULL,

    -- Quantidade de pontos acumulados pelo usuário
    saldo_pontos NUMBER DEFAULT 0 NOT NULL,

    -- Status da conta do usuário
    status_usuario VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,

    -- Restrição para permitir apenas valores válidos no status
    CONSTRAINT ck_usuario_status CHECK (status_usuario IN ('ATIVO','INATIVO','BLOQUEADO'))
);

-- ========================
-- TABELA: PONTO_COLETA
-- Armazena os locais onde os usuários podem realizar descartes.
-- ========================
CREATE TABLE PONTO_COLETA (
    -- Chave primária da tabela PONTO_COLETA
    id_ponto_coleta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome do ponto de coleta
    nome_ponto VARCHAR2(120) NOT NULL,

    -- Descrição do ponto de coleta
    descricao VARCHAR2(255),

    -- Horário de funcionamento do ponto
    horario_funcionamento VARCHAR2(100),

    -- Status do ponto de coleta
    status_ponto VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,

    -- Chave estrangeira para o endereço do ponto
    id_endereco NUMBER NOT NULL,

    -- Relacionamento com a tabela ENDERECO
    CONSTRAINT fk_ponto_endereco FOREIGN KEY (id_endereco) REFERENCES ENDERECO(id_endereco),

    -- Garante que cada ponto de coleta tenha um endereço exclusivo
    CONSTRAINT uq_ponto_endereco UNIQUE (id_endereco),

    -- Restringe os valores possíveis para o status
    CONSTRAINT ck_ponto_status CHECK (status_ponto IN ('ATIVO','INATIVO','MANUTENCAO'))
);

-- ========================
-- TABELA: TIPO_MATERIAL
-- Armazena os tipos de materiais recicláveis aceitos.
-- ========================
CREATE TABLE TIPO_MATERIAL (
    -- Chave primária da tabela TIPO_MATERIAL
    id_tipo_material NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome do material, como plástico, papel, vidro
    nome_material VARCHAR2(80) NOT NULL UNIQUE,

    -- Descrição complementar do material
    descricao VARCHAR2(255),

    -- Quantidade de pontos recebidos por kg do material
    pontuacao_por_kg NUMBER(10,2) NOT NULL,

    -- Categoria do material
    categoria VARCHAR2(50) NOT NULL
);

-- ========================
-- TABELA: DESCARTE
-- Registra cada descarte realizado por um usuário em um ponto de coleta.
-- ========================
CREATE TABLE DESCARTE (
    -- Chave primária da tabela DESCARTE
    id_descarte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Data em que o descarte foi realizado
    data_descarte DATE DEFAULT SYSDATE NOT NULL,

    -- Peso total do descarte
    peso_total NUMBER(10,2) NOT NULL,

    -- Observações opcionais sobre o descarte
    observacao VARCHAR2(255),

    -- Status do descarte
    status_descarte VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,

    -- Usuário que realizou o descarte
    id_usuario NUMBER NOT NULL,

    -- Ponto de coleta onde ocorreu o descarte
    id_ponto_coleta NUMBER NOT NULL,

    -- Relacionamento com a tabela USUARIO
    CONSTRAINT fk_descarte_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),

    -- Relacionamento com a tabela PONTO_COLETA
    CONSTRAINT fk_descarte_ponto FOREIGN KEY (id_ponto_coleta) REFERENCES PONTO_COLETA(id_ponto_coleta),

    -- Restringe os valores possíveis para o status do descarte
    CONSTRAINT ck_descarte_status CHECK (status_descarte IN ('PENDENTE','VALIDADO','CANCELADO')),

    -- Garante que o peso não seja negativo
    CONSTRAINT ck_descarte_peso CHECK (peso_total >= 0)
);

-- ========================
-- TABELA: ITEM_DESCARTE
-- Detalha os materiais presentes dentro de um descarte.
-- ========================
CREATE TABLE ITEM_DESCARTE (
    -- Chave primária da tabela ITEM_DESCARTE
    id_item_descarte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Quantidade em kg do material descartado
    quantidade_kg NUMBER(10,2) NOT NULL,

    -- Quantidade de pontos gerados por esse item
    pontos_gerados NUMBER NOT NULL,

    -- Chave estrangeira para o descarte principal
    id_descarte NUMBER NOT NULL,

    -- Chave estrangeira para o tipo de material
    id_tipo_material NUMBER NOT NULL,

    -- Relacionamento com a tabela DESCARTE
    CONSTRAINT fk_item_descarte FOREIGN KEY (id_descarte) REFERENCES DESCARTE(id_descarte),

    -- Relacionamento com a tabela TIPO_MATERIAL
    CONSTRAINT fk_item_material FOREIGN KEY (id_tipo_material) REFERENCES TIPO_MATERIAL(id_tipo_material),

    -- Garante que a quantidade seja maior que zero
    CONSTRAINT ck_item_quantidade CHECK (quantidade_kg > 0),

    -- Garante que os pontos gerados não sejam negativos
    CONSTRAINT ck_item_pontos CHECK (pontos_gerados >= 0)
);

-- ========================
-- TABELA: EMPRESA_PARCEIRA
-- Armazena os dados das empresas que oferecem recompensas.
-- ========================
CREATE TABLE EMPRESA_PARCEIRA (
    -- Chave primária da tabela EMPRESA_PARCEIRA
    id_empresa_parceira NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome fantasia da empresa
    nome_fantasia VARCHAR2(120) NOT NULL,

    -- Razão social da empresa
    razao_social VARCHAR2(150),

    -- CNPJ único da empresa
    cnpj VARCHAR2(18) UNIQUE,

    -- Email para contato
    email_contato VARCHAR2(150),

    -- Telefone de contato
    telefone VARCHAR2(20),

    -- Status da empresa
    status_empresa VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,

    -- Restringe os valores possíveis para o status
    CONSTRAINT ck_empresa_status CHECK (status_empresa IN ('ATIVA','INATIVA'))
);

-- ========================
-- TABELA: RECOMPENSA
-- Armazena as recompensas disponíveis para resgate.
-- ========================
CREATE TABLE RECOMPENSA (
    -- Chave primária da tabela RECOMPENSA
    id_recompensa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome da recompensa
    nome_recompensa VARCHAR2(120) NOT NULL,

    -- Descrição da recompensa
    descricao VARCHAR2(255),

    -- Quantidade de pontos necessários para resgate
    pontos_necessarios NUMBER NOT NULL,

    -- Quantidade disponível em estoque
    quantidade_estoque NUMBER DEFAULT 0 NOT NULL,

    -- Validade da recompensa
    validade DATE,

    -- Status da recompensa
    status_recompensa VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,

    -- Empresa parceira responsável pela recompensa
    id_empresa_parceira NUMBER NOT NULL,

    -- Relacionamento com a tabela EMPRESA_PARCEIRA
    CONSTRAINT fk_recompensa_empresa FOREIGN KEY (id_empresa_parceira) REFERENCES EMPRESA_PARCEIRA(id_empresa_parceira),

    -- Garante que os pontos necessários sejam maiores que zero
    CONSTRAINT ck_recompensa_pontos CHECK (pontos_necessarios > 0),

    -- Garante que o estoque não seja negativo
    CONSTRAINT ck_recompensa_estoque CHECK (quantidade_estoque >= 0),

    -- Restringe os valores possíveis para o status
    CONSTRAINT ck_recompensa_status CHECK (status_recompensa IN ('ATIVA','INATIVA','ESGOTADA'))
);

-- ========================
-- TABELA: RESGATE_RECOMPENSA
-- Registra as trocas de pontos por recompensas.
-- ========================
CREATE TABLE RESGATE_RECOMPENSA (
    -- Chave primária da tabela RESGATE_RECOMPENSA
    id_resgate NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Data em que o resgate foi realizado
    data_resgate DATE DEFAULT SYSDATE NOT NULL,

    -- Quantidade de pontos utilizados no resgate
    qtd_pontos_utilizados NUMBER NOT NULL,

    -- Status do resgate
    status_resgate VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,

    -- Código único do resgate
    codigo_resgate VARCHAR2(50) NOT NULL UNIQUE,

    -- Usuário que realizou o resgate
    id_usuario NUMBER NOT NULL,

    -- Recompensa resgatada
    id_recompensa NUMBER NOT NULL,

    -- Relacionamento com a tabela USUARIO
    CONSTRAINT fk_resgate_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),

    -- Relacionamento com a tabela RECOMPENSA
    CONSTRAINT fk_resgate_recompensa FOREIGN KEY (id_recompensa) REFERENCES RECOMPENSA(id_recompensa),

    -- Garante que a quantidade de pontos utilizados seja maior que zero
    CONSTRAINT ck_resgate_pontos CHECK (qtd_pontos_utilizados > 0),

    -- Restringe os valores possíveis para o status do resgate
    CONSTRAINT ck_resgate_status CHECK (status_resgate IN ('PENDENTE','CONCLUIDO','CANCELADO'))
);

-- ========================
-- TABELA: HISTORICO_PONTOS
-- Registra toda entrada e saída de pontos dos usuários.
-- ========================
CREATE TABLE HISTORICO_PONTOS (
    -- Chave primária da tabela HISTORICO_PONTOS
    id_historico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Tipo da movimentação: ENTRADA ou SAIDA
    tipo_movimentacao VARCHAR2(20) NOT NULL,

    -- Quantidade de pontos movimentados
    pontos NUMBER NOT NULL,

    -- Data da movimentação
    data_movimentacao DATE DEFAULT SYSDATE NOT NULL,

    -- Descrição opcional da movimentação
    descricao VARCHAR2(255),

    -- Usuário relacionado à movimentação
    id_usuario NUMBER NOT NULL,

    -- Referência opcional a um descarte
    id_descarte NUMBER,

    -- Referência opcional a um resgate
    id_resgate NUMBER,

    -- Relacionamento com a tabela USUARIO
    CONSTRAINT fk_historico_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),

    -- Relacionamento com a tabela DESCARTE
    CONSTRAINT fk_historico_descarte FOREIGN KEY (id_descarte) REFERENCES DESCARTE(id_descarte),

    -- Relacionamento com a tabela RESGATE_RECOMPENSA
    CONSTRAINT fk_historico_resgate FOREIGN KEY (id_resgate) REFERENCES RESGATE_RECOMPENSA(id_resgate),

    -- Restringe o tipo de movimentação
    CONSTRAINT ck_historico_tipo CHECK (tipo_movimentacao IN ('ENTRADA','SAIDA')),

    -- Garante que a pontuação seja maior que zero
    CONSTRAINT ck_historico_pontos CHECK (pontos > 0)
);

-- ========================
-- ÍNDICES
-- Melhoram a performance de busca e relacionamento entre tabelas.
-- ========================

-- Índice para buscas por usuário nos descartes
CREATE INDEX idx_descarte_usuario ON DESCARTE(id_usuario);

-- Índice para buscas por ponto de coleta nos descartes
CREATE INDEX idx_descarte_ponto ON DESCARTE(id_ponto_coleta);

-- Índice para buscas por descarte em ITEM_DESCARTE
CREATE INDEX idx_item_descarte ON ITEM_DESCARTE(id_descarte);

-- Índice para buscas por tipo de material em ITEM_DESCARTE
CREATE INDEX idx_item_material ON ITEM_DESCARTE(id_tipo_material);

-- Índice para buscas por usuário em RESGATE_RECOMPENSA
CREATE INDEX idx_resgate_usuario ON RESGATE_RECOMPENSA(id_usuario);

-- Índice para buscas por recompensa em RESGATE_RECOMPENSA
CREATE INDEX idx_resgate_recompensa ON RESGATE_RECOMPENSA(id_recompensa);

-- Índice para buscas por usuário em HISTORICO_PONTOS
CREATE INDEX idx_historico_usuario ON HISTORICO_PONTOS(id_usuario);

-- ========================
-- DADOS INICIAIS
-- Inserts básicos para popular o sistema.
-- ========================

-- Cadastra o material plástico
INSERT INTO TIPO_MATERIAL (nome_material, descricao, pontuacao_por_kg, categoria)
VALUES ('Plástico','Resíduos plásticos recicláveis',10,'RECICLAVEL');

-- Cadastra o material papel
INSERT INTO TIPO_MATERIAL (nome_material, descricao, pontuacao_por_kg, categoria)
VALUES ('Papel','Papéis recicláveis',8,'RECICLAVEL');

-- Cadastra o material vidro
INSERT INTO TIPO_MATERIAL (nome_material, descricao, pontuacao_por_kg, categoria)
VALUES ('Vidro','Materiais de vidro',6,'RECICLAVEL');

-- Cadastra o material metal
INSERT INTO TIPO_MATERIAL (nome_material, descricao, pontuacao_por_kg, categoria)
VALUES ('Metal','Materiais metálicos',12,'RECICLAVEL');

-- Cadastra uma empresa parceira inicial
INSERT INTO EMPRESA_PARCEIRA (nome_fantasia, razao_social, cnpj, email_contato, telefone, status_empresa)
VALUES ('Eco Market','Eco Market LTDA','12345678000190','contato@eco.com','11999999999','ATIVA');

-- Cadastra uma recompensa inicial
INSERT INTO RECOMPENSA (nome_recompensa, descricao, pontos_necessarios, quantidade_estoque, validade, status_recompensa, id_empresa_parceira)
VALUES ('Cupom R$20','Desconto em loja',200,100,TO_DATE('31/12/2026','DD/MM/YYYY'),'ATIVA',1);

-- ========================
-- TRIGGERS
-- Automatizam regras do sistema no banco de dados.
-- ========================

-- Trigger responsável por atualizar automaticamente
-- o saldo de pontos do usuário quando houver inserção
-- no histórico de pontos.
CREATE OR REPLACE TRIGGER trg_historico_pontos_usuario
AFTER INSERT ON HISTORICO_PONTOS
FOR EACH ROW
BEGIN
    -- Se a movimentação for entrada, soma pontos ao usuário
    IF :NEW.tipo_movimentacao = 'ENTRADA' THEN
        UPDATE USUARIO
        SET saldo_pontos = saldo_pontos + :NEW.pontos
        WHERE id_usuario = :NEW.id_usuario;

    -- Se a movimentação for saída, subtrai pontos do usuário
    ELSIF :NEW.tipo_movimentacao = 'SAIDA' THEN
        UPDATE USUARIO
        SET saldo_pontos = saldo_pontos - :NEW.pontos
        WHERE id_usuario = :NEW.id_usuario;
    END IF;
END;
/

-- Trigger responsável por reduzir automaticamente
-- o estoque da recompensa após um resgate.
CREATE OR REPLACE TRIGGER trg_baixa_estoque_recompensa
AFTER INSERT ON RESGATE_RECOMPENSA
FOR EACH ROW
BEGIN
    UPDATE RECOMPENSA
    SET quantidade_estoque = quantidade_estoque - 1
    WHERE id_recompensa = :NEW.id_recompensa
    AND quantidade_estoque > 0;
END;
/